<?php
declare(strict_types=1);

// NovayaGazeta SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

NovayaGazetaUtility::setRegistrar(function (NovayaGazetaUtility $u): void {
    $u->clean = [NovayaGazetaClean::class, 'call'];
    $u->done = [NovayaGazetaDone::class, 'call'];
    $u->make_error = [NovayaGazetaMakeError::class, 'call'];
    $u->feature_add = [NovayaGazetaFeatureAdd::class, 'call'];
    $u->feature_hook = [NovayaGazetaFeatureHook::class, 'call'];
    $u->feature_init = [NovayaGazetaFeatureInit::class, 'call'];
    $u->fetcher = [NovayaGazetaFetcher::class, 'call'];
    $u->make_fetch_def = [NovayaGazetaMakeFetchDef::class, 'call'];
    $u->make_context = [NovayaGazetaMakeContext::class, 'call'];
    $u->make_options = [NovayaGazetaMakeOptions::class, 'call'];
    $u->make_request = [NovayaGazetaMakeRequest::class, 'call'];
    $u->make_response = [NovayaGazetaMakeResponse::class, 'call'];
    $u->make_result = [NovayaGazetaMakeResult::class, 'call'];
    $u->make_point = [NovayaGazetaMakePoint::class, 'call'];
    $u->make_spec = [NovayaGazetaMakeSpec::class, 'call'];
    $u->make_url = [NovayaGazetaMakeUrl::class, 'call'];
    $u->param = [NovayaGazetaParam::class, 'call'];
    $u->prepare_auth = [NovayaGazetaPrepareAuth::class, 'call'];
    $u->prepare_body = [NovayaGazetaPrepareBody::class, 'call'];
    $u->prepare_headers = [NovayaGazetaPrepareHeaders::class, 'call'];
    $u->prepare_method = [NovayaGazetaPrepareMethod::class, 'call'];
    $u->prepare_params = [NovayaGazetaPrepareParams::class, 'call'];
    $u->prepare_path = [NovayaGazetaPreparePath::class, 'call'];
    $u->prepare_query = [NovayaGazetaPrepareQuery::class, 'call'];
    $u->graphql_body = [NovayaGazetaGraphql::class, 'body'];
    $u->graphql_errors = [NovayaGazetaGraphql::class, 'errors'];
    $u->result_basic = [NovayaGazetaResultBasic::class, 'call'];
    $u->result_body = [NovayaGazetaResultBody::class, 'call'];
    $u->result_headers = [NovayaGazetaResultHeaders::class, 'call'];
    $u->transform_request = [NovayaGazetaTransformRequest::class, 'call'];
    $u->transform_response = [NovayaGazetaTransformResponse::class, 'call'];
});
